### ISSUE TITLE
Starting on PopOS / Ubuntu fails

### ISSUE THREAD

**Issue by eitch** [wiverson/maven-jpackage-template#15]
Fails with:
```
(TestApp:1379821): Gdk-WARNING **: 16:52:02.309: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

**Comment by eitch** [comment]
The assets from the releases https://github.com/wiverson/maven-jpackage-template/releases/tag/Ubuntu-latest fail to launch

**Comment by wiverson** [comment]
If you check out the project on PopOS and run mvn install with a local build, does it work?

**Comment by eitch** [comment]
Yes, i have the exact same issue after running a mvn install and then installing the generated testapp_21.13.71736-1_amd64.deb file

**Comment by wiverson** [comment]
Doh. Whatever is going on is at the JavaFX/Linux level. I had never heard of PopOS before, not sure what's going on.

A few thoughts: if it's something to do with the desktop integration samples, try replacing this line in BaseApplication.java:

```
private final Plugin[] plugins = new Plugin[]{new StandardMenus(), new HelloWorld(), new FileDrop(),
            new DesktopIntegration(), new LogFile(), new DarkMode()};
```

with something like this:

```
private final Plugin[] plugins = new Plugin[]{};
```

...and see if that fixes it. I'd be a little surprised, however, as by default the plugins are started with an exception wrapper to help guard against that sort of thing.

Another suggestion would be to try going through the JavaFX docs at https://openjfx.io and see if you can get a Hello World working there first. If you can get the Hello World to launch but not this template let me know.

You could also try reaching out to the folks at https://gluonhq.com for support.

**Comment by eitch** [comment]
Hi @wiverson i was able to locate the issue. The problem is the DesktopIntegration plugin. After i commented it out, i was able to build, install and then run the TestApp from the debian package.

I guess 

PopOS is basically Ubuntu, with a few changes, e.g. drivers and is sold with computers from System76.

**Comment by wiverson** [comment]
That's really interesting. Do you have the full stack trace from the launch failure?

**Comment by eitch** [comment]
This is what i get when running with maven:

	$ mvn clean javafx:run
	[INFO] Scanning for projects...
	[INFO] 
	[INFO] ---------------< com.changenode:maven-jpackage-template >---------------
	[INFO] Building maven-jpackage-template 1.0-SNAPSHOT
	[INFO] --------------------------------[ jar ]---------------------------------
	[INFO] 
	[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ maven-jpackage-template ---
	[INFO] Deleting /home/eitch/src/compile_temp/maven-jpackage-template/target
	[INFO] 
	[INFO] >>> javafx-maven-plugin:0.0.5:run (default-cli) > process-classes @ maven-jpackage-template >>>
	[INFO] 
	[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ maven-jpackage-template ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] Using 'UTF-8' encoding to copy filtered properties files.
	[INFO] Copying 4 resources to /home/eitch/src/compile_temp/maven-jpackage-template/target/packaging
	[INFO] 
	[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ maven-jpackage-template ---
	[INFO] Changes detected - recompiling the module!
	[INFO] Compiling 9 source files to /home/eitch/src/compile_temp/maven-jpackage-template/target/classes
	[INFO] 
	[INFO] <<< javafx-maven-plugin:0.0.5:run (default-cli) < process-classes @ maven-jpackage-template <<<
	[INFO] 
	[INFO] 
	[INFO] --- javafx-maven-plugin:0.0.5:run (default-cli) @ maven-jpackage-template ---

	(java:1610216): Gdk-WARNING **: 21:50:10.790: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
	[ERROR] Command execution failed.
	org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
	    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
	    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:553)
	    at org.openjfx.JavaFXBaseMojo.executeCommandLine (JavaFXBaseMojo.java:420)
	    at org.openjfx.JavaFXRunMojo.execute (JavaFXRunMojo.java:105)
	    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
	    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
	    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
	    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
	    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
	    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
	    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
	    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
	    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
	    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
	    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:78)
	    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke (Method.java:567)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
	org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
		at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
		at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
		at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:553)
		at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:420)
		at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:105)
		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
		at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:567)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time:  1.653 s
	[INFO] Finished at: 2021-03-22T21:50:11+01:00
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.5:run (default-cli) on project maven-jpackage-template: Error: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
	[ERROR] 
	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
	[ERROR] 
	[ERROR] For more information about the errors and possible solutions, please read the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by wiverson** [comment]
You are getting a build time error....?  Huh. That's not what I would
expect at all. That's really strange. Interesting that it's not showing up
on the GitHub Action runners. Glad you have a workaround for now, this
might take a while to sort out.

**Comment by eitch** [comment]
Hi @wiverson, no no, i get that error when running javafx:run, which will start the app after compiling, etc. It is a runtime error.

**Comment by wiverson** [comment]
Oh, right.

Is the app getting far enough along to generate a debugX.log file in your home directory?  By default the template does that to help with debugging these issues...

**Comment by eitch** [comment]
I do have this:

	Exception in Application start method
	java.lang.reflect.InvocationTargetException
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:567)
		at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
		at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:567)
		at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
	Caused by: java.lang.RuntimeException: Exception in Application start method
		at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
		at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
		at java.base/java.lang.Thread.run(Thread.java:831)
	Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.MenuItem.removeEventHandler(javafx.event.EventType, javafx.event.EventHandler)" because "<parameter1>" is null
		at javafx.controls/javafx.scene.control.skin.MenuBarSkin.updateActionListeners(MenuBarSkin.java:816)
		at javafx.controls/javafx.scene.control.skin.MenuBarSkin.rebuildUI(MenuBarSkin.java:825)
		at javafx.controls/javafx.scene.control.skin.MenuBarSkin.<init>(MenuBarSkin.java:355)
		at javafx.controls/javafx.scene.control.MenuBar.createDefaultSkin(MenuBar.java:202)
		at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
		at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
		at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
		at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
		at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
		at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
		at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
		at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
		at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
		at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
		at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
		at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
		at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9547)
		at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
		at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1747)
		at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
		at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
		at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1111)
		at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
		at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
		at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1187)
		at javafx.graphics/javafx.stage.Window.show(Window.java:1202)
		at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
		at com.changenode.BaseApplication.start(BaseApplication.java:98)
		at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
		at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
		at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
		at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
		at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
		at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
		at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
		... 1 more
	Exception running application com.changenode.BaseApplication
